### ISSUE TITLE
Module 4 - the FrontEnd -  no output after clicking the Search button

### ISSUE THREAD

**Issue by zdarova** [aws-samples/semantic-search-with-amazon-opensearch#18]
In the Module 4, at the end, there is no output from the search button, even though in the notebook I had no errors.

amzn alias: alerail

**Comment by leejianwei** [comment]
Let me have a look

**Comment by leejianwei** [comment]
Tested again and no issue. Make sure you follow the guide when you run the lab.

**Comment by johncolmdoyle** [comment]
Just to leave a comment here, the readme states that the stack name shouldn't be changed, but made no mention of changing the default password.

If the password is changed, this will cause an issue in Module 4 where the API Gateway/Lambda has the initial default password hard coded, causing 401 response from Opensearch, and UI getting a CORs error due to the internal exception.
